name: test
on:
  workflow_dispatch
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.6.0
    - name: start
      run: python test.py
